### PR TITLE
Replace pnet_packet with rips-packets

### PR DESCRIPTION
**Pull request by faern**
Hi!

I have been contributing to `pnet` earlier and when I saw you used that crate here I thought I could help a bit. `pnet_packet` is pretty cool, but it's not really maintained any more and it has huge and outdated dependencies. For this reason I wrote `rips-packets` many months back as part of my project to write a pure userspace IP stack in Rust (called `rips`). That project kind of died, but I did more or less finish my very light weight packet header manipulation library. Some early benchmarks hint that `rips-packets` is somewhere around 5x to 8x faster than `pnet_packet` at runtime for getting and setting header fields.

I didn't publish `rips-packets` until now when I saw a concrete use case for it.

This PR cuts the debug compile time of `wireguard-rs` in half on my laptop, since it's not depending on `syntex` and other heavy crates any more. Should hopefully help in making development easier.

*Disclaimer*: I'm an employee at Mullvad VPN, but `rips`, `rips-packets` and this PR are all my own private work. I'm in the #wireguard IRC channel if you want to discuss this code.

### CODE REVIEW

**Comment by mcginty** [comment]
So sorry I didn't notice this PR - I wasn't setup to get notifications for it since I wasn't an owner.

I had no idea about `rips` - this is awesome since like you said `pnet` is very bloated. I'll check out the crate, patch looks good!

**Comment by faern** [comment]
To be clear about `rips`. The IP stack in general is very very far from complete. And it's in the middle of a rewrite. But `rips-packets`, the part that parses out and manipulate packet headers should be fully working, hence why I published that part to crates.io.

**Comment by mcginty** [comment]
Yep, but all we need is solid packet parsing thanks to @zx2c4 designing WireGuard at the right layer 😉. Skimmed over the code yesterday and it's looking good so far.

**Comment by faern** [comment]
I rebased and solved the merge conflict. I also had to update the `snow` dependency since the commit it was pointing to in `Cargo.lock` does not exist.

**Comment by mcginty** [comment]
Code looks good in both your crate and this PR - you made it easy with the interface being roughly the same to `pnet-packet` :).

Thanks much for the PR!

**Pull request closed without merging**
