### PR TITLE
Add protocol implementation and wg-standalone

### PR DESCRIPTION
**Pull request by sopium**
I have changed license to GPL-3+, as we have discussed.

I have also replaced the “do not use” section with some weaker warnings. Is that OK with you, @zx2c4?

### CODE REVIEW

**Comment by zx2c4** [comment]
I'd recommend:

1) Keeping my "do not use" section as is, not changing it. Removing it isn't okay yet.
2) Removing "wg-standalone" and focus efforts on implementing [xplatform](https://www.wireguard.io/xplatform/). It's fine if you use wg-standalone locally on your system, or something, for development, but I don't want to introduce any fragmentation, so it doesn't belong in this repo.
3) GPLv2+ is better, since it allows for more compatibility with other codebases, but if you insist on GPLv3+, then I guess that's fine.

**Comment by sopium** [comment]
Alright, I will remove `wg-standalone` and keep the “do not use”.

I am not motivated enough to implement the `xplatform` interface myself, but I will add the necessary state manipulation and query functions, hopefully soon.

I think GPL-3.0 actually has a better and clearer compability story, e.g., with Apache 2. Nevertheless, I get to decide the license for my code, and I am going with GPL-3.0+.

For the record, do you agree with the license change, @saschagrunert?

**Comment by saschagrunert** [comment]
Thank you very much for the contribution! :+1: Yes, I agree with the license change and will focus my contribution on the xplatform implementation.

**Comment by zx2c4** [comment]
Great so, looking forward to v2 of this and then we'll get rolling from that basis.

**Comment by sopium** [comment]
“The necessary state manipulation and query functions” is there! Albeit totally untested.

I am gonna landing this to master if there are no objections?

**Comment by zx2c4** [comment]
Land it all!

**Pull request merged**
